meta:
  version: 1.0
data:
  method: mysql
  mysql:
    host: localhost
    port: 3306
    username: minecraft
    password: ''
    database: minecraft
    prefix: 'snitch_'
autoclean:
  enable: true
  actions:
  - 'before 365d'
  - 'actions flow before 7d'
defaults:
  area: 20
  time: 30m
tools:
  wand: GOLD_PICKAXE
  wand-block: BEDROCK
disabled-logging:
- 'XP_PICKUP'